version: "3.8"

services:

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - techretail_net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  backend:
    image: node:18-alpine
    command: >
      node -e "
      const http = require('http');
      http.createServer((req, res) => {
        res.writeHead(200, {'Content-Type': 'application/json'});
        res.end(JSON.stringify({status: 'ok', service: 'TechRetail API'}));
      }).listen(3000);
      console.log('Backend corriendo en puerto 3000');
      "
    networks:
      - techretail_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    secrets:
      - db_password

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: techretail_db
    networks:
      - techretail_net
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
    secrets:
      - db_password

  cache:
    image: redis:7-alpine
    networks:
      - techretail_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - techretail_net
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  techretail_net:
    driver: overlay

volumes:
  db_data:

secrets:
  db_password:
    external: true
